//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp11.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int idManufacturer { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public int Quantity { get; set; }
        

        public string FullViewName
        {
            get
            {
                return "Название: " + this.Name;
            }
        }
        public string FullViewManufacturer
        {
            get
            {
                return "Производитель: " + this.Manufacturer.Name;
            }
        }
        public string FullViewDescription
        {
            get
            {
                return "Описание: " + this.Description;
            }
        }
        public string FullViewPrice
        {
            get
            {
                return "Стоимость: " + Convert.ToString(this.Price) + " руб.";
            }
        }
        public string FullViewDiscount
        {
            get
            {
                if (Discount == null)
                {
                    return string.Empty;
                }
                else
                {
                    return "Скидка: " + Convert.ToString(this.Discount) + "%";
                }
            }
        }

        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
